# Tensroflow 2.0

In [ ]:
!pip install -q tensorflow-gpu==2.0.0-rc1

In [1]:
samples = ['너 오늘 이뻐 보인다',
          '나는 오늘 기분이 더러워',
          '끝내주는데, 좋은 일이 있나봐',
          '나 좋은 일이 생겼어',
          '아 오늘 진짜 짜증나',
          '환상적인데, 정말 좋은거 같아']

targets =[[1], [0], [1], [1], [0], [1]]

In [2]:
import os
import tensorflow as tf
import numpy as np

from tensorflow.keras import preprocessing

In [3]:
print(tf.__version__)

2.0.0


In [8]:
tokenizer = preprocessing.text.Tokenizer() 
tokenizer.fit_on_texts(samples) 
sequences = tokenizer.texts_to_sequences(samples)
input_sequences = preprocessing.sequence.pad_sequences(sequences, maxlen = 6, padding='post')

labels = np.array(targets)

word_index = tokenizer.word_index

print(f"index text data : \n{input_sequences}\n")
print(f"shape of sequences:{input_sequences.shape}")
print(f"shape of labels:{labels.shape}")

index text data : 
[[ 4  1  5  6  0  0]
 [ 7  1  8  9  0  0]
 [10  2  3 11  0  0]
 [12  2  3 13  0  0]
 [14  1 15 16  0  0]
 [17 18 19 20  0  0]]

shape of sequences:(6, 6)
shape of labels:(6, 1)


## Using Keras Sequential

In [9]:
from tensorflow.keras import backend
from tensorflow.keras import layers

In [10]:
batch_size = 2
num_epochs = 100

In [11]:
vocab_size = len(word_index) + 1
emb_size = 128
hidden_dimension = 256
output_dimension = 1

In [8]:
model = tf.keras.Sequential([
layers.Embedding(vocab_size, emb_size, input_length = 6),
layers.Lambda(lambda x: tf.reduce_mean(x, axis = 1)),
layers.Dense(hidden_dimension, activation='relu'),
layers.Dense(output_dimension, activation='sigmoid')])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 6, 128)            2688      
_________________________________________________________________
lambda (Lambda)              (None, 128)               0         
_________________________________________________________________
dense (Dense)                (None, 256)               33024     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 257       
Total params: 35,969
Trainable params: 35,969
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.fit(input_sequences, labels, epochs=num_epochs, batch_size=batch_size)

Train on 6 samples
Epoch 1/100
6/6 [==============================] - 0s 78ms/sample - loss: 0.6916 - accuracy: 0.6667
Epoch 2/100
6/6 [==============================] - 0s 998us/sample - loss: 0.6766 - accuracy: 0.6667
Epoch 3/100
6/6 [==============================] - 0s 1ms/sample - loss: 0.6620 - accuracy: 0.6667
Epoch 4/100
6/6 [==============================] - 0s 871us/sample - loss: 0.6464 - accuracy: 0.6667
Epoch 5/100
6/6 [==============================] - 0s 952us/sample - loss: 0.6327 - accuracy: 0.6667
Epoch 6/100
6/6 [==============================] - 0s 948us/sample - loss: 0.6121 - accuracy: 0.6667
Epoch 7/100
6/6 [==============================] - 0s 1ms/sample - loss: 0.5896 - accuracy: 1.0000
Epoch 8/100
6/6 [==============================] - 0s 952us/sample - loss: 0.5636 - accuracy: 1.0000
Epoch 9/100
6/6 [==============================] - 0s 939us/sample - loss: 0.5339 - accuracy: 1.0000
Epoch 10/100
6/6 [==============================] - 0s 956us/sample - loss: 0

## Using Keras Functional API

In [12]:
inputs = layers.Input(shape = (6, ))
embed_output = layers.Embedding(vocab_size, emb_size)(inputs)
pooled_output = tf.reduce_mean(embed_output, axis=1)
hidden_layer = layers.Dense(hidden_dimension, activation='relu')(pooled_output)
outputs = layers.Dense(output_dimension, activation='sigmoid')(hidden_layer)

In [13]:
model = tf.keras.Model(inputs=inputs, outputs=outputs)

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [14]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 6)]               0         
_________________________________________________________________
embedding_2 (Embedding)      (None, 6, 128)            2688      
_________________________________________________________________
tf_op_layer_Mean_1 (TensorFl [(None, 128)]             0         
_________________________________________________________________
dense_3 (Dense)              (None, 256)               33024     
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 257       
Total params: 35,969
Trainable params: 35,969
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.fit(input_sequences, labels, epochs=num_epochs, batch_size=batch_size)

Train on 6 samples
Epoch 1/100
6/6 [==============================] - 0s 54ms/sample - loss: 0.7015 - accuracy: 0.1667
Epoch 2/100
6/6 [==============================] - 0s 968us/sample - loss: 0.6877 - accuracy: 0.6667
Epoch 3/100
6/6 [==============================] - 0s 964us/sample - loss: 0.6778 - accuracy: 1.0000
Epoch 4/100
6/6 [==============================] - 0s 903us/sample - loss: 0.6636 - accuracy: 1.0000
Epoch 5/100
6/6 [==============================] - 0s 897us/sample - loss: 0.6532 - accuracy: 1.0000
Epoch 6/100
6/6 [==============================] - 0s 903us/sample - loss: 0.6394 - accuracy: 1.0000
Epoch 7/100
6/6 [==============================] - 0s 880us/sample - loss: 0.6233 - accuracy: 1.0000
Epoch 8/100
6/6 [==============================] - 0s 919us/sample - loss: 0.6045 - accuracy: 1.0000
Epoch 9/100
6/6 [==============================] - 0s 883us/sample - loss: 0.5838 - accuracy: 1.0000
Epoch 10/100
6/6 [==============================] - 0s 913us/sample - los

## Build Custom Model

In [30]:
class CustomModel(tf.keras.Model):

    def __init__(self, vocab_size, embed_dimension, hidden_dimension, output_dimension):
        super(Custom, self).__init__(name='my_model')
        self.embedding = layers.Embedding(vocab_size, embed_dimension)
        self.dense_layer = layers.Dense(hidden_dimension, activation='relu')
        self.output_layer = layers.Dense(output_dimension, activation='sigmoid')

    def call(self, inputs):
        x = self.embedding(inputs)
        x = tf.reduce_mean(x, axis=1)
        x = self.dense_layer(x)
        x = self.output_layer(x)
        
        return x

In [31]:
model = CustomModel(vocab_size = vocab_size,
            embed_dimension=emb_size,
            hidden_dimension=hidden_dimension,
            output_dimension=output_dimension)

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(input_sequences, labels, epochs=num_epochs, batch_size=batch_size)

Train on 6 samples
Epoch 1/100
6/6 [==============================] - 0s 49ms/sample - loss: 0.6956 - accuracy: 0.3333
Epoch 2/100
6/6 [==============================] - 0s 755us/sample - loss: 0.6780 - accuracy: 0.6667
Epoch 3/100
6/6 [==============================] - 0s 912us/sample - loss: 0.6629 - accuracy: 0.6667
Epoch 4/100
6/6 [==============================] - 0s 865us/sample - loss: 0.6504 - accuracy: 0.6667
Epoch 5/100
6/6 [==============================] - 0s 1ms/sample - loss: 0.6358 - accuracy: 0.6667
Epoch 6/100
6/6 [==============================] - 0s 960us/sample - loss: 0.6183 - accuracy: 0.6667
Epoch 7/100
6/6 [==============================] - 0s 942us/sample - loss: 0.6000 - accuracy: 0.6667
Epoch 8/100
6/6 [==============================] - 0s 921us/sample - loss: 0.5779 - accuracy: 0.6667
Epoch 9/100
6/6 [==============================] - 0s 830us/sample - loss: 0.5468 - accuracy: 0.6667
Epoch 10/100
6/6 [==============================] - 0s 1ms/sample - loss: 0

## Using Custiom Layer

In [18]:
class CustomLayer(layers.Layer):

    def __init__(self, hidden_dimension, output_dimension, **kwargs):
        self.hidden_dimension = hidden_dimension
        self.output_dimension = output_dimension
        super(CustomLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.dense_layer1 = layers.Dense(self.hidden_dimension, activation = 'relu')
        self.dense_layer2 = layers.Dense(self.output_dimension)

    def call(self, inputs):
        hidden_output = self.dense_layer1(inputs)
        return self.dense_layer2(hidden_output)

    # Optional
    def get_config(self):
        base_config = super(CustomLayer, self).get_config()
        base_config['hidden_dim'] = self.hidden_dimension
        base_config['output_dim'] = self.output_dim
        return base_config

    @classmethod
    def from_config(cls, config):
        return cls(**config)

In [19]:
model = tf.keras.Sequential([
    layers.Embedding(vocab_size, emb_size, input_length = 6),
    layers.Lambda(lambda x: tf.reduce_mean(x, axis = 1)),
    CustomLayer(hidden_dimension, output_dimension),
    layers.Activation('sigmoid')])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(input_sequences, labels, epochs=num_epochs, batch_size=batch_size)

Train on 6 samples
Epoch 1/100
6/6 [==============================] - 0s 51ms/sample - loss: 0.6940 - accuracy: 0.3333
Epoch 2/100
6/6 [==============================] - 0s 976us/sample - loss: 0.6811 - accuracy: 0.8333
Epoch 3/100
6/6 [==============================] - 0s 872us/sample - loss: 0.6697 - accuracy: 0.6667
Epoch 4/100
6/6 [==============================] - 0s 977us/sample - loss: 0.6576 - accuracy: 0.6667
Epoch 5/100
6/6 [==============================] - 0s 929us/sample - loss: 0.6448 - accuracy: 1.0000
Epoch 6/100
6/6 [==============================] - 0s 955us/sample - loss: 0.6299 - accuracy: 1.0000
Epoch 7/100
6/6 [==============================] - 0s 1ms/sample - loss: 0.6152 - accuracy: 1.0000
Epoch 8/100
6/6 [==============================] - 0s 1ms/sample - loss: 0.5927 - accuracy: 1.0000
Epoch 9/100
6/6 [==============================] - 0s 984us/sample - loss: 0.5689 - accuracy: 1.0000
Epoch 10/100
6/6 [==============================] - 0s 1ms/sample - loss: 0.5

## Using tf.data.Dataset

In [36]:
dataset = tf.data.Dataset.from_tensor_slices((input_sequences, labels))
dataset = dataset.batch(batch_size)
dataset = dataset.shuffle(len(sequences))

In [37]:
model.fit(dataset, epochs=100)

Epoch 1/100
3/3 [==============================] - 0s 86ms/step - loss: 7.0392e-04 - accuracy: 1.0000
Epoch 2/100
3/3 [==============================] - 0s 5ms/step - loss: 5.6593e-04 - accuracy: 1.0000
Epoch 3/100
3/3 [==============================] - 0s 5ms/step - loss: 5.5462e-04 - accuracy: 1.0000
Epoch 4/100
3/3 [==============================] - 0s 5ms/step - loss: 5.4387e-04 - accuracy: 1.0000
Epoch 5/100
3/3 [==============================] - 0s 5ms/step - loss: 5.3251e-04 - accuracy: 1.0000
Epoch 6/100
3/3 [==============================] - 0s 6ms/step - loss: 6.1856e-04 - accuracy: 1.0000
Epoch 7/100
3/3 [==============================] - 0s 6ms/step - loss: 5.1339e-04 - accuracy: 1.0000
Epoch 8/100
3/3 [==============================] - 0s 5ms/step - loss: 5.9667e-04 - accuracy: 1.0000
Epoch 9/100
3/3 [==============================] - 0s 6ms/step - loss: 4.9640e-04 - accuracy: 1.0000
Epoch 10/100
3/3 [==============================] - 0s 6ms/step - loss: 7.2705e-04 - accur

## Using tf.data.Dataset with validation set

In [42]:
model = tf.keras.Sequential([
    layers.Embedding(vocab_size, emb_size, input_length = 6),
    layers.Lambda(lambda x: tf.reduce_mean(x, axis = 1)),
    CustomLayer(hidden_dimension, output_dimension),
    layers.Activation('sigmoid')])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [43]:
validation_input_sequences = input_sequences[-3:]
validation_labels = labels[-3:]

In [44]:
print(f'shape of train sequence: {input_sequences.shape}')
print(f'shape of train labels: {labels.shape}')
print(f'shape of validation sequence: {validation_input_sequences.shape}')
print(f'shape of validation labels: {validation_labels.shape}')

shape of train sequence: (6, 6)
shape of train labels: (6, 1)
shape of validation sequence: (3, 6)
shape of validation labels: (3, 1)


In [45]:
dataset = tf.data.Dataset.from_tensor_slices((input_sequences, labels))
dataset = dataset.batch(batch_size)
dataset = dataset.shuffle(len(sequences))

val_dataset = tf.data.Dataset.from_tensor_slices((validation_input_sequences, validation_labels))
val_dataset = val_dataset.batch(batch_size)

model.fit(dataset, epochs=num_epochs,
          validation_data=val_dataset)

Epoch 1/100
3/3 [==============================] - 0s 152ms/step - loss: 0.6924 - accuracy: 0.5000 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 2/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6763 - accuracy: 0.6667 - val_loss: 0.6649 - val_accuracy: 0.6667
Epoch 3/100
3/3 [==============================] - 0s 7ms/step - loss: 0.6628 - accuracy: 0.6667 - val_loss: 0.6508 - val_accuracy: 1.0000
Epoch 4/100
3/3 [==============================] - 0s 7ms/step - loss: 0.6627 - accuracy: 0.8333 - val_loss: 0.6364 - val_accuracy: 1.0000
Epoch 5/100
3/3 [==============================] - 0s 8ms/step - loss: 0.6380 - accuracy: 1.0000 - val_loss: 0.6203 - val_accuracy: 1.0000
Epoch 6/100
3/3 [==============================] - 0s 8ms/step - loss: 0.6209 - accuracy: 1.0000 - val_loss: 0.6012 - val_accuracy: 1.0000
Epoch 7/100
3/3 [==============================] - 0s 9ms/step - loss: 0.6031 - accuracy: 1.0000 - val_loss: 0.5779 - val_accuracy: 1.0000
Epoch 8/100
3/3 [