# placeholder  구현 하기

### 긍정/부정 Make data (긍정: 1, 부정: 0)

---



In [24]:
samples = ['너 오늘 이뻐 보인다',
          '나는 오늘 기분이 더러워',
          '끝내주는데, 좋은 일이 있나봐',
          '나 오늘 좋은 일이 생겼어',
          '아 진짜 짜증나',
          '오, 이거 진짜 좋은 것 같은데']

targets = [[1], [0], [1], [1], [0], [1]]

### load need modules

In [25]:
import os
import tensorflow as tf
import numpy as np

from tensorflow.keras import preprocessing

### Data Preprocessing

In [29]:
tokenizer = preprocessing.text.Tokenizer() 
tokenizer.fit_on_texts(samples) 
sequences = tokenizer.texts_to_sequences(samples)
sequences = preprocessing.sequence.pad_sequences(sequences, maxlen = 6, padding='post')

targets = np.array(targets)

print("index text data : \n", sequences)
print("shape of sequences:", sequences.shape)

index text data : 
 [[ 4  1  5  6  0  0]
 [ 7  1  8  9  0  0]
 [10  2  3 11  0  0]
 [12  2  3 13  0  0]
 [14  1 15 16  0  0]
 [17 18 19 20  0  0]]
shape of sequences: (6, 6)


In [30]:
word_index = tokenizer.word_index

print("index of each word : \n", word_index)

index of each word : 
 {'오늘': 1, '좋은': 2, '일이': 3, '너': 4, '이뻐': 5, '보인다': 6, '나는': 7, '기분이': 8, '더러워': 9, '끝내주는데': 10, '있나봐': 11, '나': 12, '생겼어': 13, '아': 14, '진짜': 15, '짜증나': 16, '환상적인데': 17, '정말': 18, '좋은거': 19, '같아': 20}


In [35]:
print("targets: \n", targets)
print("shape of targets:", targets.shape) 

targets: 
 [[1]
 [0]
 [1]
 [1]
 [0]
 [1]]
shape of targets: (6, 1)


### feed_dict data processing
<b> 장점 : TensorFlow 외부에서 데이터 처리를 수행하여 Python으로 쉽게 처리 할 수 있다.  
<b> 단점 : 사용자는 종종 단일 스레드에서 데이터를 처리하고 실행 속도를 저하시키는 데이터 병목 현상을 만든다.

### placeholder define

In [76]:
inputs_ph = tf.placeholder(dtype=tf.int32, shape=[6], name='sequences')
labels_ph = tf.placeholder(dtype=tf.int32, shape=[1], name='labels')

### Session run



In [77]:
with tf.Session() as sess:
    for i in range(len(sequences)):
        sequence_input, label = sess.run([inputs_ph, labels_ph],
                                         feed_dict = {inputs_ph: sequences[i], labels_ph: targets[i]})
        print('='*40)
        print('Sequence input:', sequence_input)
        print('Label:', label)
    print('='*40)

Sequence input: [4 1 5 6 0 0]
Label: [1]
Sequence input: [7 1 8 9 0 0]
Label: [0]
Sequence input: [10  2  3 11  0  0]
Label: [1]
Sequence input: [12  2  3 13  0  0]
Label: [1]
Sequence input: [14  1 15 16  0  0]
Label: [0]
Sequence input: [17 18 19 20  0  0]
Label: [1]


### shuffle data

In [ ]:
# <Your code>

with tf.Session() as sess:
    for i in random_index:
        # <Your code>
        print('='*40)
        print('Sequence input:', sequence_input)
        print('Label:', label)
    print('='*40)

### make batch

In [ ]:
batch_size = 2

# <Your code>
    
with tf.Session() as sess:
    for i in range(0, len(sequences), batch_size):
        # <Your code>
        print('='*40)
        print('Sequence input:', sequence_input)
        print('Label:', label)
    print('='*40)

###  2 epoch

In [82]:
total_epoch = 2

with tf.Session() as sess:
    for epoch in range(total_epoch):
        print(f'\n{epoch}epoch start')
        for i in range(len(sequences)):
            sequence_input, label = sess.run([inputs_ph, labels_ph],
                                             feed_dict = {inputs_ph: sequences[i], labels_ph: targets[i]})
            print('='*40)
            print('Sequence input:', sequence_input)
            print('Label:', label)
        print('='*40)


0epoch start
Sequence input: [4 1 5 6 0 0]
Label: [1]
Sequence input: [7 1 8 9 0 0]
Label: [0]
Sequence input: [10  2  3 11  0  0]
Label: [1]
Sequence input: [12  2  3 13  0  0]
Label: [1]
Sequence input: [14  1 15 16  0  0]
Label: [0]
Sequence input: [17 18 19 20  0  0]
Label: [1]

1epoch start
Sequence input: [4 1 5 6 0 0]
Label: [1]
Sequence input: [7 1 8 9 0 0]
Label: [0]
Sequence input: [10  2  3 11  0  0]
Label: [1]
Sequence input: [12  2  3 13  0  0]
Label: [1]
Sequence input: [14  1 15 16  0  0]
Label: [0]
Sequence input: [17 18 19 20  0  0]
Label: [1]
